### ISSUE TITLE
unnecessary dependencies?

### ISSUE THREAD

**Issue by corybrunson** [alstat/ALUES#19]
I'm not clear on whether the ggmap and raster packages are required for [the 7th vignette](https://alstat.github.io/ALUES/articles/a07_visual_maps.html). I was unable to install ggmap due to an outdated R installation, but i was able to knit the vignette file after commenting out both `library(ggmap)` and `library(raster)`. Are these packages indeed necessary, or can they be dropped from the vignette and from the package `Suggests` list? (I apologize if the answer is obvious; i don't use these packages myself.)

_Part of [this JOSS review](https://github.com/openjournals/joss-reviews/issues/4228)._

**Comment by alstat** [comment]
Hi @corybrunson, both are required. The reason why the knitting works without it, follows from the fact that the figures generated for the maps are actually saved images. We don't really run the code to generate the images because it would take time, so we decided to save the output and simply call it into the vignette. However, if you need to run the code in the console, by copy-pasting, then you really have to load both `ggmap` and `raster`.

**Comment by corybrunson** [comment]
Aha, thank you, that clarifies.
